### ISSUE TITLE
Does the 'GTBbox' mean the bbox generated by MTCNN or the coordinates in annotation?

### ISSUE THREAD

**Issue by PlumedSerpent** [protossw512/AdaptiveWingLoss#3]
Hi, thanks for sharing your implementation. I am kinda confused about the  'GTBbox'  in the result table. Does it mean the bbox generated by the  MTCNN detector?

**Comment by protossw512** [comment]
As shown in the paper, GTBbox means faces are cropped according to ground truth landmarks.

**Comment by PlumedSerpent** [comment]
How can I switch to GTBbox in your test code?

**Comment by protossw512** [comment]
@PlumedSerpent To do this you will need to use min, max of the groundtruth landmarks to find minx, miny, maxx, maxy, instead of reading these from label files. However, I would not recommend you to do this. In real-world applications, you only have bounding boxes from a face detector. If you want to do research, other works also use the detection bounding boxes for benchmarking.
